name: CI

on:
  push:
    branches: [ main, dev, 'feature/**' ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Frontend build
        working-directory: frontend
        run: |
          npm i -g pnpm
          pnpm install
          pnpm build

      - name: Backend install
        working-directory: backend
        run: |
          npm i -g pnpm
          pnpm install
          echo "Backend ready"
